name: test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: beta
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Write env file
        run: |
          for i in ${{vars}}; do
            echo "$i=${{vars.$i}}" >> .env
          done
          
      
        
