name: test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Write env file
        run: |
          for var_i in $(vars); do
            echo "${var_i}=${var_i}" >> .env
          done
      - name: Read env file
        run: |
          cat .env
      
        
